'use strict';

exports.wcc={
	path:'public/webcomponents',
	list: [{
		id:'helloWorld',
		file:'hello-world.html'
	},{
		id:'lifeCycle',
		file:'lifeCycle.html'
	},{
		id:'bussinesCard',
		file:'bussinesCard.html'
	},{
		id:'myCard',
		file:'myCard.html'
	},{
		id:'myButton',
		file:'extendedButton.html'
	},{
		id: 'basicProps',
		file:'basicProperties.html'
	},{
		id:'DataBindingParentToChildParent',
		file:'DataBindingParentToChildParent.html'
	},{
		id:'DataBindingParentToChildChild',
		file:'DataBindingParentToChildChild.html'
	},{
		id: 'twoWaysDataBindingParent',
		file:'twoWaysDataBindingParent.html'
	},{
		id:'twoWaysDataBindingChild',
		file:'twoWaysDataBindingChild.html'
	},{
		id:'ForceDataBindingPtCParent',
		file:'ForceDataBindingPtCParent.html'
	},{
		id:'ForceDataBindingPtCChild',
		file:'ForceDataBindingPtCChild.html'
	},{
		id:'DataBindingChildToParentParent',
		file:'DataBindingChildToParentParent.html'
	},{
		id:'DataBindingChildToParentChild',
		file:'DataBindingChildToParentChild.html'
	},{
		id:'observer',
		file:'Observer.html'
	},{
		id:'eventsListeners',
		file:'eventListeners.html'
	},{
		id:'CustomEvent',
		file:'CustomEvent.html'
	},{
		id:'checkIncrease',
		file:'checkIncrease.html'
	},{
		id:'listComponent',
		file:'listComponent.html'
	}]
}